=== artemeon/core/module_packagemanager/docs/xsd/package_v2.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2016 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
            <xs:element type="constantsType" name="constants" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constantsType">
        <xs:sequence>
            <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="value" type="xs:integer"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== artemeon/core/module_search/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>search</title>
    <description>The module search provides a full-text search for both, backend and portal. It respects permissions and status of all records.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
        <module name="packagemanager" version="7.0" />
    </requiredModules>
    <constants>
        <constant name="_search_module_id_" value="55" />
    </constants>
</package>

=== artemeon/core/module_chartjs/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>chartjs</title>
    <description>chartjs charting engine. Used to render charts on the client-side, based on the common Chart.js library.</description>
    <version>7.1</version>
    <author>Artemeon Team</author>
    <type>MODULE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants />
</package>

=== artemeon/core/module_jqplot/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>jqplot</title>
    <description>jqPlot charting engine. Used to render charts on the client-side, based on the common jqPlot library.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants />
</package>

=== artemeon/core/module_fileindexer/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>fileindexer</title>
    <description>Tool to index file content.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="mediamanager" version="7.1" />
        <module name="search" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_fileindexer_module_id_" value="1510915351" />
    </constants>

</package>

=== artemeon/core/module_workflows/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>workflows</title>
    <description>A complex workflow-engine to trigger events by multiple triggers.</description>
    <version>7.1.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_workflows_module_id_" value="115" />
    </constants>
</package>

=== artemeon/core/module_ntlmauth/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>ntlmauth</title>
    <description>Module to enable ntlm sso logins</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_ntlmauth_module_id_" value="20190903" />
    </constants>
</package>

=== artemeon/core/module_tinyurl/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
>
    <title>tinyurl</title>
    <description>Create a shortened URL</description>
    <version>7.0</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants>
        <constant name="_tinyurl_module_id_" value="20180907" />
    </constants>
</package>

=== artemeon/core/module_basicauthentication/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
>
    <title>_buildfilesNew</title>
    <description>Adds support for basic http authentication. Therefore an event-listener checks for authentication headers when processing the request and tries to login the user.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants></constants>
</package>
