=== artemeon/core/module_packagemanager/docs/xsd/package_v2.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2016 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
            <xs:element type="constantsType" name="constants" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constantsType">
        <xs:sequence>
            <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="value" type="xs:integer"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== artemeon/core/module_ezcchart/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>ezcchart</title>
    <description>ezComponents charting engine. Used to render charts on the server-side, generating an image. Makes use of the ezComponents library.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants />
</package>

=== artemeon/core/module_mediamanager/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>mediamanager</title>
    <description>
        The mediamanager is a central place to handle all kind of files. This includes images for galleries or even a download-manager.
        If you have the package "qr-code" installed, the download links may be illustrated using a qrcode-image, too.
        The mediamanager replaces the old (v3) download- and gallery-modules.
    </description>
    <version>7.0</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants>
        <constant name="_mediamanager_module_id_" value="130" />
        <constant name="_mediamanager_folderview_modul_id_" value="13" />
    </constants>
</package>

=== artemeon/core/module_oauth2/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>oauth2</title>
    <description>Module to enable OAuth2 integration</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants>
        <constant name="_oauth2_module_id_" value="20181024" />
    </constants>
</package>

=== artemeon/core/module_api/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>api</title>
    <description>Provides an entry point to access API endpoints</description>
    <version>1.0</version>
    <author>Artemeon Team</author>
    <type>MODULE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
</package>

=== artemeon/core/module_v4skin/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>v4skin</title>
    <description>The basic v4 admin-skin.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_v4skin_module_id_" value="20170212" />
    </constants>
</package>

=== artemeon/core/module_benchmark/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>benchmark</title>
    <description>Simple scripts to validate a systems' performance</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants />
</package>
