=== artemeon/core/module_packagemanager/docs/xsd/package_v2.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2016 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
            <xs:element type="constantsType" name="constants" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constantsType">
        <xs:sequence>
            <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="value" type="xs:integer"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== artemeon/core/module_comments/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
>
    <title>comments</title>
    <description>TODO Description </description>
    <version>7.0</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
        <module name="packagemanager" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_comments_module_id_" value="20191030" />
    </constants>
</package>

=== artemeon/core/module_tags/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>tags</title>
    <description>Tags are used to connect objects with keywords.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_tags_modul_id_" value="95" />
    </constants>
</package>

=== artemeon/core/module_packagemanager/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>packagemanager</title>
    <description>The packagemanager wraps all logic to handle packages on the client side. The packagemanager handles the local update and installation of packages.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_packagemanager_module_id_" value="2" />
    </constants>
</package>

=== artemeon/core/_buildfilesNew/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
>
    <title>basicauthentication</title>
    <description>Adds support for basic http authentication. Therefore an event-listener checks for authentication headers when processing the request and tries to login the user.</description>
    <version>7.1</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <type>MODULE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
</package>

=== artemeon/core/module_dbbrowser/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
    >
    <title>dbrowser</title>
    <description>Visualizes the current database structure</description>
    <version>7.0</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0.1" />
    </requiredModules>
    <constants>
        <constant name="_dbbrowser_module_id_" value="20180808" />
    </constants>
</package>

=== artemeon/core/module_ldap/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>ldap</title>
    <description>Connects the installation to a ldap directory. Refer to the config-file for all options.</description>
    <version>7.0</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.0" />
    </requiredModules>
    <constants>
        <constant name="_ldap_module_id_" value="16" />
    </constants>
</package>

=== artemeon/core/module_devops/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>devops</title>
    <description>Common systeminfo plugins</description>
    <version>7.1</version>
    <author>ARTEMEON</author>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="7.1" />
    </requiredModules>
    <constants>
        <constant name="_devops_module_id_" value="20160916" />
    </constants>
</package>

=== artemeon/core/module_system/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://apidocs.kajona.de/xsd/package_v2.xsd"
        >
    <title>system</title>
    <description>Core of the Kajona framework. By default, the system-packages includes several modules, e.g. system, permissions, user, messaging and languages.

When updating from 5.0 to 5.1 or performing another major update from x.x to x.y, make sure to use the upgrade script instead of the internal package management. See https://www.kajona.de/updateguide.html for details.

    </description>
    <version>7.1.1</version>
    <author>Kajona Team</author>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules />
    <constants>
        <constant name="_system_modul_id_" value="0" />
        <constant name="_user_modul_id_" value="15" />
        <constant name="_languages_modul_id_" value="65" />
        <constant name="_messaging_module_id_" value="135" />
    </constants>

</package>
